name: Test

on:
  push:
    branch:
      - '**'
      - 'master'

  workflow_dispatch:
    branch:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.16.x]

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: pnpm install

    - name: Test API lib
      run: pnpm test-api-lib --browsers=ChromeHeadless --watch=false

    - name: Test TG APP
      run: pnpm test-tg-app --browsers=ChromeHeadless --watch=false
